---

- name: Configure interfaces 
  eos_config:
   src: spine-interfaces.j2
   provider: "{{ eos_connection }}"
   match: none
   save: yes

- name: Configure BGP underlay
  eos_config:
   src: spine-bgp-under.j2
   provider: "{{ eos_connection }}"
   match: none
   save: yes

- name: Configure BGP Overlay
  eos_config:
   src: spine-bgp-over.j2
   provider: "{{ eos_connection }}"
   match: none
   save: yes

